all:
  children:
    testBox:
      hosts:
        192.168.122.70:
        192.168.122.168:
        192.168.122.163:#anya has a nice booty
      vars:
        ansible_become_user: f
        ansible_password: f

    fedora:
      hosts:
        192.168.122.247:
      vars:
        ansible_become_user: f
        ansible_password: f

